default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres

development:
  <<: *default
  database: back_end_development

test:
  <<: *default
  database: back_end_test

production:
  <<: *default
  database: back_end_production
