version: '3.8'

services:
  db:
    image: postgres:9.6.18-alpine
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
 
  app:
    depends_on:
      - 'db'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ".:/forms"
      - gems:/gems

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes: 
  db:
  gems:


    